version: '3'
services:
  website:
    container_name: ADMINISTRATION_WEBSITE
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '$VITE_FRONTEND_PORT:$VITE_FRONTEND_PORT'

networks:
  mynetwork:
    driver: bridge
