#!/bin/bash
set -e

POSTGRES_USER="$POSTGRES_USER"
POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
POSTGRES_DB="$POSTGRES_DB"

if [ -z "$POSTGRES_USER" ] || [ -z "$POSTGRES_PASSWORD" ] || [ -z "$POSTGRES_DB" ]; then
  echo "Faltan variables de entorno. Asegúrate de configurar POSTGRES_USER, POSTGRES_PASSWORD y POSTGRES_DB."
  exit 1
fi

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE IF NOT EXISTS $POSTGRES_DB;"
psql -U "$POSTGRES_USER" -c "CREATE USER IF NOT EXISTS $POSTGRES_USER WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';"
psql -U "$POSTGRES_USER" -c "ALTER ROLE $POSTGRES_USER SET client_encoding TO 'utf8';"
psql -U "$POSTGRES_USER" -c "ALTER ROLE $POSTGRES_USER SET default_transaction_isolation TO 'read committed';"
psql -U "$POSTGRES_USER" -c "ALTER ROLE $POSTGRES_USER SET timezone TO 'UTC';"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;"

exec "$@"
