version: '3'
services:
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - '$POSTGRES_PORT:$POSTGRES_PORT'
    # entrypoint: ['./init.sh', 'postgres']
    networks:
      - my-docker-network

  backend_app:
    container_name: ADMINISTRATION_SERVER
    depends_on:
      - postgres_db
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '$SERVER_PORT:$SERVER_PORT'
    networks:
      - my-docker-network

volumes:
  postgres_db:
    name: postgres_db

networks:
  my-docker-network:
    driver: bridge
