version: '3'
services:
  # postgres:
  #   image: postgres:14-alpine
  #   build:
  #     context: .
  #   volumes:
  #     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_USER: main-panel_test
  #     POSTGRES_PASSWORD: main-panel_test
  #     POSTGRES_DB: main-panel_test
  #   ports:
  #     - '5432:5432' # Puerto de PostgreSQL fijo
  #   # entrypoint: ['./init.sh', 'postgres']

  backend_app:
    container_name: ADMINISTRATION_SERVER
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '$SERVER_PORT:$SERVER_PORT'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge